# Application-Level Alerting Rules
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: krakengaming-application-alerts
  namespace: default
  labels:
    app: krakengaming
    component: monitoring
spec:
  groups:
  - name: application.critical
    interval: 30s
    rules:
    - alert: ServiceDown
      expr: up{job=~"krakengaming-.*"} == 0
      for: 1m
      labels:
        severity: critical
        service: "{{ $labels.job }}"
      annotations:
        summary: "Service {{ $labels.job }} is down"
        description: "Service {{ $labels.job }} has been down for more than 1 minute"
        runbook_url: "https://runbooks.krakengaming.org/service-down"

    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
      for: 2m
      labels:
        severity: critical
        service: "{{ $labels.service }}"
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} for service {{ $labels.service }}"
        runbook_url: "https://runbooks.krakengaming.org/high-error-rate"

    - alert: DatabaseConnectionFailure
      expr: database_connections_failed_total > 0
      for: 1m
      labels:
        severity: critical
        service: database
      annotations:
        summary: "Database connection failures detected"
        description: "{{ $value }} database connection failures in the last minute"
        runbook_url: "https://runbooks.krakengaming.org/database-issues"

  - name: application.warning
    interval: 1m
    rules:
    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        service: "{{ $labels.service }}"
      annotations:
        summary: "High latency detected"
        description: "95th percentile latency is {{ $value }}s for service {{ $labels.service }}"
        runbook_url: "https://runbooks.krakengaming.org/high-latency"

    - alert: MemoryUsageHigh
      expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.8
      for: 5m
      labels:
        severity: warning
        container: "{{ $labels.container }}"
      annotations:
        summary: "High memory usage"
        description: "Memory usage is {{ $value | humanizePercentage }} for container {{ $labels.container }}"
        runbook_url: "https://runbooks.krakengaming.org/memory-usage"

    - alert: DiscordBotOffline
      expr: discord_bot_connected == 0
      for: 2m
      labels:
        severity: warning
        service: discord-bot
      annotations:
        summary: "Discord bot is offline"
        description: "Discord bot has been offline for more than 2 minutes"
        runbook_url: "https://runbooks.krakengaming.org/discord-bot-offline"

  - name: application.info
    interval: 5m
    rules:
    - alert: UnusualTrafficPattern
      expr: rate(http_requests_total[10m]) > 1.5 * rate(http_requests_total[1h] offset 1h)
      for: 10m
      labels:
        severity: info
        service: "{{ $labels.service }}"
      annotations:
        summary: "Unusual traffic pattern detected"
        description: "Traffic is 50% higher than usual for service {{ $labels.service }}"
        runbook_url: "https://runbooks.krakengaming.org/traffic-analysis"

    - alert: SlowDatabaseQueries
      expr: mysql_global_status_slow_queries_total > 10
      for: 15m
      labels:
        severity: info
        service: database
      annotations:
        summary: "Slow database queries detected"
        description: "{{ $value }} slow queries detected in the last 15 minutes"
        runbook_url: "https://runbooks.krakengaming.org/slow-queries"
