steps:
  # Build the backend Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'apps/backend/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/backend-preview'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/backend-preview'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'krakengaming-backend-preview'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backend-preview'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port=4000'
      - '--set-env-vars'
      - 'NODE_ENV=preview,HOST=0.0.0.0,CORS_ALLOWED_ORIGINS=https://krakengaming-frontend-preview-7235ln35zq-uc.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/backend-preview'
