steps:
  # Install dependencies and build
  - name: 'node:20'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd apps/discord-bot
        npm install
        npm run build

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'kraken-discord-bot'
      - '--source'
      - 'apps/discord-bot'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--set-secrets'
      - 'DISCORD_BOT_TOKEN=discord-bot-token:latest,DISCORD_CLIENT_ID=discord-client-id:latest,DISCORD_CLIENT_SECRET=discord-client-secret:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,LOG_LEVEL=info'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '2'
      - '--timeout'
      - '3600'

options:
  logging: CLOUD_LOGGING_ONLY
