name: Update Dependencies

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggers

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Update npm dependencies
      run: |
        # Update all workspaces
        npm update

        # Check for major version updates
        npx npm-check-updates -u --target minor

        # Install updated dependencies
        npm install

    - name: Run tests after dependency updates
      run: |
        # Run tests to ensure updates don't break functionality
        npm run lint
        npm run test

    - name: Check for changes
      id: changes
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates

          This PR contains automated dependency updates. Please review the changes and ensure all tests pass before merging.

          ### Changes Made:
          - Updated npm dependencies to latest minor/patch versions
          - Verified that all tests continue to pass

          ### Testing:
          - [ ] All linting checks pass
          - [ ] All unit tests pass
          - [ ] Integration tests pass (run manually if needed)
          - [ ] No breaking changes introduced

          Auto-generated by GitHub Actions 🤖
        branch: chore/dependency-updates
        delete-branch: true

  security-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: |
        # Run npm audit and generate report
        npm audit --audit-level=moderate --json > audit-report.json || true

        # Check for high/critical vulnerabilities
        CRITICAL_VULNS=$(npm audit --audit-level=critical --json | jq '.metadata.vulnerabilities.critical // 0')
        HIGH_VULNS=$(npm audit --audit-level=high --json | jq '.metadata.vulnerabilities.high // 0')

        echo "Critical vulnerabilities: $CRITICAL_VULNS"
        echo "High vulnerabilities: $HIGH_VULNS"

        if [ $CRITICAL_VULNS -gt 0 ] || [ $HIGH_VULNS -gt 0 ]; then
          echo "::error::High or critical security vulnerabilities found!"
          npm audit
          exit 1
        fi

    - name: Upload audit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-report
        path: audit-report.json
